### ISSUE TITLE
验签失败，请重新登录

### ISSUE THREAD

**Issue by chengengfengC** [AD-feiben/blog-ssr#1]
你好，怎么在本地跑，请求文章列表怎么一直返回 ： 验签失败，请重新登录

**Comment by AD-feiben** [comment]
接口地址是哪个？

**Comment by AD-feiben** [comment]
> 你好，怎么在本地跑，请求文章列表怎么一直返回 ： 验签失败，请重新登录

接口地址是哪个

**Comment by AD-feiben** [comment]
接口地址是哪个呢

**Comment by chengengfengC** [comment]
本地 localhost:3000，对应的blog-server的地址，

**Comment by AD-feiben** [comment]
![image](https://user-images.githubusercontent.com/19575477/45481850-2ee09580-b77f-11e8-870d-34954bd906dc.png)
blog-server  src/middleware/index.js 这里已经设置了不验文章列表这个接口了，是不是改了什么东西

**Comment by chengengfengC** [comment]
![image](https://user-images.githubusercontent.com/28992807/45533122-280e5d00-b829-11e8-8c0f-0aeafbc0a7d1.png)
没有，克隆你的整个项目就改了这个地方

**Comment by AD-feiben** [comment]
这个地址是我用nginx做转发的，你们不需要加api
